package com.mbeddr.cpp.cext.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class CppStandardHeaderImport_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("#include <");
    this.append(SPropertyOperations.getString(node, "name"));
    this.append(">");
  }
}
