package com.mbeddr.cpp.classes.findUsages;

/*Generated by MPS */

import jetbrains.mps.ide.findusages.BaseFindUsagesDescriptor;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;

public class FindUsagesDescriptor extends BaseFindUsagesDescriptor {
  public FindUsagesDescriptor() {
    super(PersistenceFacade.getInstance().createModuleReference("31b871c8-3ba6-4751-8c9e-b20f99ee6b69(com.mbeddr.cpp.classes)"), PersistenceFacade.getInstance().createModelReference("r:cd2f73e4-7968-47ea-ba22-86ea9418d6ce(com.mbeddr.cpp.classes.findUsages)"));
  }

  public void init() {
    add(new findSubclasses_Finder(), "374287044671790292");
  }
}
