package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class CppStandardHeaderImport_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IIdentifierNamedConcept_BehaviorDescriptor {
  public CppStandardHeaderImport_BehaviorDescriptor() {
  }

  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept thisConcept) {
    return IIdentifierNamedConcept_Behavior.virtual_allowNonIdentifierNames_6584628407655574550(thisConcept);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.cext.structure.CppStandardHeaderImport";
  }
}
