package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IResolveInfo_BehaviorDescriptor;

public interface ICppIdentifierNamedConcept_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor, IResolveInfo_BehaviorDescriptor {
}
