package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface INamespaceProviderReference_BehaviorDescriptor extends ICppIdentifierNamedConcept_BehaviorDescriptor {
  public SNode virtual_getNamespaceProvider_3710575327008827950(SNode thisNode);
}
