package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IVisibleElementProvider_BehaviorDescriptor;

public interface INamespaceScoper_BehaviorDescriptor extends IVisibleElementProvider_BehaviorDescriptor {
}
