package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.util.NameUtil;

public class NamespaceScopeType_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Iterable<SNode> virtual_visibleContentsOfType_7139820346881179813(SNode thisNode, final SNode targetConcept) {
    return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "outer", true), "com.mbeddr.cpp.cext.structure.NamespaceType"), "nsprovider", false), "virtual_getAllContents_4315577761883431846", new Object[]{})).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, NameUtil.nodeFQName(targetConcept));
      }
    });
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "outer", true), "virtual_getPresentation_1213877396640", new Object[]{}) + "::" + BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "inner", true), "virtual_getPresentation_1213877396640", new Object[]{});
  }

  public static int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return 500;
  }
}
