package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.BinaryExpression_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IVisibleElementProvider_BehaviorDescriptor;
import com.mbeddr.core.expressions.behavior.IStopReshuffling_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import com.mbeddr.core.base.behavior.IVisibleElementProvider_Behavior;

public class NamespaceScopeExpr_BehaviorDescriptor extends BinaryExpression_BehaviorDescriptor implements IVisibleElementProvider_BehaviorDescriptor, IStopReshuffling_BehaviorDescriptor, INamespaceScoper_BehaviorDescriptor, IDontSubstituteByDefault_BehaviorDescriptor {
  public NamespaceScopeExpr_BehaviorDescriptor() {
  }

  public Object virtual_evaluateStatically_7863679314024402271(SNode thisNode) {
    return NamespaceScopeExpr_Behavior.virtual_evaluateStatically_7863679314024402271(thisNode);
  }

  public int virtual_getPriolevel_6584628407655574558(SConcept thisConcept) {
    return NamespaceScopeExpr_Behavior.virtual_getPriolevel_6584628407655574558(thisConcept);
  }

  public boolean virtual_hasVisibleContentsOfType_9136994893370299109(SNode thisNode, SNode targetConcept) {
    return IVisibleElementProvider_Behavior.virtual_hasVisibleContentsOfType_9136994893370299109(thisNode, targetConcept);
  }

  public boolean virtual_isLValue_7254843406768839725(SNode thisNode) {
    return NamespaceScopeExpr_Behavior.virtual_isLValue_7254843406768839725(thisNode);
  }

  public boolean virtual_isStaticallyEvaluatable_3788988821852141811(SNode thisNode) {
    return NamespaceScopeExpr_Behavior.virtual_isStaticallyEvaluatable_3788988821852141811(thisNode);
  }

  public Iterable<SNode> virtual_visibleContentsOfType_7139820346881179813(SNode thisNode, SNode targetConcept) {
    return NamespaceScopeExpr_Behavior.virtual_visibleContentsOfType_7139820346881179813(thisNode, targetConcept);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.cext.structure.NamespaceScopeExpr";
  }
}
