package com.mbeddr.cpp.cext.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class NamespaceType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements INestedNamespaceRef_BehaviorDescriptor {
  public NamespaceType_BehaviorDescriptor() {
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return NamespaceType_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.cext.structure.NamespaceType";
  }
}
