package com.mbeddr.cpp.cext.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class CppImplementationModule_Constraints extends BaseConstraintsDescriptor {
  public CppImplementationModule_Constraints() {
    super("com.mbeddr.cpp.cext.structure.CppImplementationModule");
  }
}
