package com.mbeddr.cpp.cext.constraints;

/*Generated by MPS */

import java.util.regex.Pattern;

public class NamespaceHelper {
  private static Pattern validName = Pattern.compile("([a-zA-Z0-9$[_][-]]+)((:{2})[a-zA-Z0-9$[_][-]]+)*");

  public static boolean isValidNamespace(String namespace) {
    return validName.matcher(namespace).matches();
  }
}
