package com.mbeddr.cpp.classes.typesystem;

/*Generated by MPS */


public class DebugMemberAccessTypeSystem {
  private static boolean ENABLE = false;

  public static void debug(String s) {
    if (!(ENABLE)) {
      return;
    }

    System.out.println(s + " - " + DebugMemberAccessTypeSystem.class.getName());
  }
}
