package com.mbeddr.cpp.classes.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class addBaseClass_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public addBaseClass_Intention() {
  }

  public String getConcept() {
    return "com.mbeddr.cpp.classes.structure.ClassDeclaration";
  }

  public String getPresentation() {
    return "addBaseClass";
  }

  public String getPersistentStateKey() {
    return "com.mbeddr.cpp.classes.intentions.addBaseClass_Intention";
  }

  public String getLanguageFqName() {
    return "com.mbeddr.cpp.classes";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:82dd6aa6-7b0e-4d3f-ac7e-a3ce4807a3b1(com.mbeddr.cpp.classes.intentions)", "8616684942293620472");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new addBaseClass_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Add Base Class";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SLinkOperations.addNewChild(node, "inheritanceDefinitions", "com.mbeddr.cpp.classes.structure.InheritanceDefinition");
    }

    public IntentionDescriptor getDescriptor() {
      return addBaseClass_Intention.this;
    }
  }
}
