package com.mbeddr.cpp.classes.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import com.mbeddr.cpp.classes.behavior.ClassDeclaration_Behavior;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.intentions.IntentionDescriptor;

public class makeClassNotCopiableNotAssignable_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public makeClassNotCopiableNotAssignable_Intention() {
  }

  public String getConcept() {
    return "com.mbeddr.cpp.classes.structure.ClassDeclaration";
  }

  public String getPresentation() {
    return "makeClassNotCopiableNotAssignable";
  }

  public String getPersistentStateKey() {
    return "com.mbeddr.cpp.classes.intentions.makeClassNotCopiableNotAssignable_Intention";
  }

  public String getLanguageFqName() {
    return "com.mbeddr.cpp.classes";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return ClassDeclaration_Behavior.call_isCopyable_7540295501294968521(node) || ClassDeclaration_Behavior.call_isAssignable_7540295501294968212(node);
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:82dd6aa6-7b0e-4d3f-ac7e-a3ce4807a3b1(com.mbeddr.cpp.classes.intentions)", "7540295501295046619");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new makeClassNotCopiableNotAssignable_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Forbid Copy/Assignment";
    }

    public void execute(final SNode node, final EditorContext editorContext) {

      ClassDeclaration_Behavior.call_removeDeclarationsForCopyingAndAssignment_7540295501295123293(node);

      if ((SLinkOperations.getTarget(node, "privateMemberList", true) == null)) {
        SLinkOperations.setTarget(node, "privateMemberList", SConceptOperations.createNewNode("com.mbeddr.cpp.classes.structure.PrivateMemberList", null), true);
      }

      ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(node, "privateMemberList", true), "members", true)).addElement(ClassDeclaration_Behavior.call_makeAssignmentOverload_7540295501294914853(node));
      ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(node, "privateMemberList", true), "members", true)).addElement(ClassDeclaration_Behavior.call_makeCopyConstructor_7540295501294914924(node));

    }

    public IntentionDescriptor getDescriptor() {
      return makeClassNotCopiableNotAssignable_Intention.this;
    }
  }
}
