package com.mbeddr.cpp.classes.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import com.mbeddr.cpp.classes.behavior.Field_Behavior;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import com.mbeddr.cpp.cext.behavior.CppImplementationModule_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class renameFieldConventionally_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public renameFieldConventionally_Intention() {
  }

  public String getConcept() {
    return "com.mbeddr.cpp.classes.structure.Field";
  }

  public String getPresentation() {
    return "renameFieldConventionally";
  }

  public String getPersistentStateKey() {
    return "com.mbeddr.cpp.classes.intentions.renameFieldConventionally_Intention";
  }

  public String getLanguageFqName() {
    return "com.mbeddr.cpp.classes";
  }

  public IntentionType getType() {
    return IntentionType.ERROR;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return Field_Behavior.call_isNamedConventionally_158014820112568484(node) == false;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:82dd6aa6-7b0e-4d3f-ac7e-a3ce4807a3b1(com.mbeddr.cpp.classes.intentions)", "158014820112568474");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new renameFieldConventionally_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Rename Field Conventionally";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SNode namingConventions = CppImplementationModule_Behavior.call_getNamingConventions_158014820112486891(SNodeOperations.getAncestor(node, "com.mbeddr.cpp.cext.structure.CppImplementationModule", false, false));

      String newName = Field_Behavior.call_getCapName_158014820112622153(node);

      SPropertyOperations.set(node, "name", SPropertyOperations.getString(namingConventions, "MemberPrefix") + newName);

    }

    public IntentionDescriptor getDescriptor() {
      return renameFieldConventionally_Intention.this;
    }
  }
}
