package com.mbeddr.cpp.classes.constraints;

/*Generated by MPS */


public class DebugMethodRelatedConstraints {
  private static boolean ENABLED = false;

  public static void debug(String str) {
    if (!(ENABLED)) {
      return;
    }

    System.out.println(str + " - " + DebugMethodRelatedConstraints.class.getName());

  }
}
