package com.mbeddr.cpp.classes.constraints;

/*Generated by MPS */


public class DebugClassConcept {
  private static boolean ENABLED = false;
  private static boolean DebugClassConstraints = false;
  private static boolean DebugClassBehavior = false;
  private static boolean DebugAllBaseClassesAlgorithm = false;

  public DebugClassConcept() {
  }

  public static void DebugClassConstraints(String s) {
    if (DebugClassConstraints) {
      println(s + " -- class constraints");
    }
  }

  public static void DebugClassBehavior(String s) {
    if (DebugClassBehavior) {
      println(s + " -- class behavior");
    }
  }

  public static void DebudAllBasClassesAlgorithm(String s) {
    if (DebugAllBaseClassesAlgorithm) {
      println(s + " -- all base classes algorithm");
    }
  }

  private static void println(String s) {
    if (ENABLED) {
      System.out.println(s);
    }
  }
}
