package com.mbeddr.cpp.classes.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNodePointer;

public class NewArrayExpression_Constraints extends BaseConstraintsDescriptor {
  public NewArrayExpression_Constraints() {
    super("com.mbeddr.cpp.classes.structure.NewArrayExpression");
  }

  @Override
  public boolean hasOwnCanBeParentMethod() {
    return true;
  }

  @Override
  public boolean canBeParent(SNode node, @Nullable SNode childNode, SNode childConcept, SNode link, IOperationContext operationContext, @Nullable CheckingNodeContext checkingNodeContext) {
    boolean result = static_canBeAParent(node, childNode, childConcept, link, operationContext);

    if (!(result) && checkingNodeContext != null) {
      checkingNodeContext.setBreakingNode(canBeParentBreakingPoint);
    }

    return result;
  }

  public static boolean static_canBeAParent(SNode node, SNode childNode, SNode childConcept, SNode link, final IOperationContext operationContext) {


    if (link == SLinkOperations.findLinkDeclaration("com.mbeddr.cpp.classes.structure.NewArrayExpression", "allocatedType")) {
      if (SNodeOperations.isInstanceOf(childNode, "com.mbeddr.cpp.classes.structure.ClassifierType")) {
        // TODO check availability of the default constructor 
      }
    } else if (link == SLinkOperations.findLinkDeclaration("com.mbeddr.cpp.classes.structure.NewArrayExpression", "sizeExpression")) {
      // TODO Size should be something like int64t 
    }

    return true;

  }

  private static SNodePointer canBeParentBreakingPoint = new SNodePointer("r:5713504b-b269-4946-8fca-49fcca934ac1(com.mbeddr.cpp.classes.constraints)", "291176927575683674");
}
