package com.mbeddr.cpp.classes.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;

public class TemplateParamType_Constraints extends BaseConstraintsDescriptor {
  public TemplateParamType_Constraints() {
    super("com.mbeddr.cpp.classes.structure.TemplateParamType");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("param", new BaseReferenceConstraintsDescriptor("param", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            SNode templated = ListSequence.fromList(SNodeOperations.getAncestors(_context.getEnclosingNode(), "com.mbeddr.cpp.classes.structure.ICanBeInTemplateContext", true)).findFirst(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return BehaviorReflection.invokeVirtual(Boolean.TYPE, it, "virtual_residesInTemplateContext_998890089994455159", new Object[]{});
              }
            });
            if (templated != null) {
              Iterable<SNode> parameters = Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), templated, "virtual_getAllTemplateParameters_7069250747273260302", new Object[]{})).where(new IWhereFilter<SNode>() {
                public boolean accept(SNode it) {
                  return SNodeOperations.isInstanceOf(it, "com.mbeddr.cpp.classes.structure.TemplateClassParameter");
                }
              });
              return parameters;
            }
            return new ArrayList<SNode>();
          }

          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_40jqle_a0a1a0a0a1a0b0a1a1;
          }
        };
      }
    });
    return references;
  }

  private static SNodePointer breakingNode_40jqle_a0a1a0a0a1a0b0a1a1 = new SNodePointer("r:5713504b-b269-4946-8fca-49fcca934ac1(com.mbeddr.cpp.classes.constraints)", "8675670401742714824");
}
