package com.mbeddr.cpp.cext.pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.projectplugins.BaseProjectPlugin;
import java.util.List;
import jetbrains.mps.plugins.prefs.BaseProjectPrefsComponent;
import com.intellij.openapi.project.Project;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class PluginSolution_ProjectPlugin extends BaseProjectPlugin {
  public PluginSolution_ProjectPlugin() {
  }

  public List<BaseProjectPrefsComponent> createPreferencesComponents(Project project) {
    List<BaseProjectPrefsComponent> components = ListSequence.fromList(new ArrayList<BaseProjectPrefsComponent>());

    ListSequence.fromList(components).addElement(new CppProperty_PreferencesComponent(project));
    return components;
  }
}
