package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IModuleContent_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IFunctionLike_BehaviorDescriptor;
import com.mbeddr.cpp.cext.behavior.IRequiresCPPModule_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.core.modules.behavior.IModuleContent_Behavior;
import org.jetbrains.mps.openapi.language.SConcept;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import java.util.List;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.lang.traceable.behavior.TraceableConcept_Behavior;
import com.mbeddr.core.modules.behavior.IFunctionLike_Behavior;
import com.mbeddr.core.modules.behavior.ICodeLocationAware_Behavior;

public abstract class AbstractMethodImplementation_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IModuleContent_BehaviorDescriptor, IFunctionLike_BehaviorDescriptor, IThisContainer_BehaviorDescriptor, ICanBeInTemplateContext_BehaviorDescriptor, IRequiresCPPModule_BehaviorDescriptor {
  public AbstractMethodImplementation_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_allReferencedModuleContents_1798411515023042202(SNode thisNode) {
    return IModuleContent_Behavior.virtual_allReferencedModuleContents_1798411515023042202(thisNode);
  }

  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept thisConcept) {
    return IIdentifierNamedConcept_Behavior.virtual_allowNonIdentifierNames_6584628407655574550(thisConcept);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public SNode virtual_createImportedProxy_55677248263987031(SNode thisNode) {
    return IModuleContent_Behavior.virtual_createImportedProxy_55677248263987031(thisNode);
  }

  public boolean virtual_exportable_6584628407655574574(SConcept thisConcept) {
    return IModuleContent_Behavior.virtual_exportable_6584628407655574574(thisConcept);
  }

  public Iterable<SNode> virtual_getAllTemplateParameters_7069250747273260302(SNode thisNode) {
    return AbstractMethodImplementation_Behavior.virtual_getAllTemplateParameters_7069250747273260302(thisNode);
  }

  public List<SNode> virtual_getCommentConcept_6584628407655574603(SConcept thisConcept) {
    return IModuleContent_Behavior.virtual_getCommentConcept_6584628407655574603(thisConcept);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return AbstractMethodImplementation_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  @Nullable
  public String virtual_getTraceableProperty_5067982036267369901(SNode thisNode) {
    return TraceableConcept_Behavior.virtual_getTraceableProperty_5067982036267369901(thisNode);
  }

  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return IFunctionLike_Behavior.virtual_getUniquelyNamedElements_5095889050031059923(thisNode);
  }

  public void virtual_initNodeID_5114214484368231284(SNode thisNode, SNode originalNode) {
    ICodeLocationAware_Behavior.virtual_initNodeID_5114214484368231284(thisNode, originalNode);
  }

  public String virtual_kindString_6641971848870642999(SNode thisNode) {
    return IModuleContent_Behavior.virtual_kindString_6641971848870642999(thisNode);
  }

  public String virtual_mangledNameNew_7475861851228904359(SNode thisNode) {
    return IModuleContent_Behavior.virtual_mangledNameNew_7475861851228904359(thisNode);
  }

  public String virtual_mangledName_1317894735999377422(SNode thisNode) {
    return IModuleContent_Behavior.virtual_mangledName_1317894735999377422(thisNode);
  }

  public String virtual_nativeCodeLocation_5114214484368231257(SNode thisNode) {
    return ICodeLocationAware_Behavior.virtual_nativeCodeLocation_5114214484368231257(thisNode);
  }

  public boolean virtual_needsReferenceQualifier_1317894735999315639(SNode thisNode, SNode sourceModule) {
    return IModuleContent_Behavior.virtual_needsReferenceQualifier_1317894735999315639(thisNode, sourceModule);
  }

  public boolean virtual_preventNameMangling_6708182213627106041(SNode thisNode) {
    return AbstractMethodImplementation_Behavior.virtual_preventNameMangling_6708182213627106041(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public String virtual_referenceQualifier_1317894735999315602(SNode thisNode) {
    return IModuleContent_Behavior.virtual_referenceQualifier_1317894735999315602(thisNode);
  }

  public boolean virtual_residesInTemplateContext_998890089994455159(SNode thisNode) {
    return ICanBeInTemplateContext_Behavior.virtual_residesInTemplateContext_998890089994455159(thisNode);
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  public int virtual_sortWeight_7999989049973036118(SNode thisNode) {
    return IModuleContent_Behavior.virtual_sortWeight_7999989049973036118(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.AbstractMethodImplementation";
  }

  public abstract String virtual_presentedName_6970149437188808803(SNode thisNode);
}
