package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.cpp.cext.behavior.IRequiresCPPModule_BehaviorDescriptor;
import com.mbeddr.cpp.cext.behavior.IReferencableByNamespaceResolutionOperator_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;

public class ClassDeclaration_BehaviorDescriptor extends Classifier_BehaviorDescriptor implements IRequiresCPPModule_BehaviorDescriptor, IReferencableByNamespaceResolutionOperator_BehaviorDescriptor, IClassMember_BehaviorDescriptor {
  public ClassDeclaration_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_allMembersOfThisClassOnly_1022708226502685404(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_allMembersOfThisClassOnly_1022708226502685404(thisNode);
  }

  public Iterable<SNode> virtual_allSuperclasses_1022708226502698814(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_allSuperclasses_1022708226502698814(thisNode);
  }

  public boolean virtual_exportable_6584628407655574574(SConcept thisConcept) {
    return ClassDeclaration_Behavior.virtual_exportable_6584628407655574574(thisConcept);
  }

  public Iterable<SNode> virtual_externallyVisibleMembers_1022708226502685437(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_externallyVisibleMembers_1022708226502685437(thisNode);
  }

  public Iterable<SNode> virtual_getAllContents_4315577761883431846(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_getAllContents_4315577761883431846(thisNode);
  }

  public Iterable<SNode> virtual_getContents_8928893569897447072(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_getContents_8928893569897447072(thisNode);
  }

  public String virtual_getPresentationAfterNamespaceResolutionOperator_4315577761883429928(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_getPresentationAfterNamespaceResolutionOperator_4315577761883429928(thisNode);
  }

  public Iterable<SNode> virtual_members_1022708226502685371(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_members_1022708226502685371(thisNode);
  }

  public int virtual_sortWeight_7999989049973036118(SNode thisNode) {
    return ClassDeclaration_Behavior.virtual_sortWeight_7999989049973036118(thisNode);
  }

  public Iterable<SNode> virtual_visibleContentsOfType_7139820346881179813(SNode thisNode, SNode targetConcept) {
    return ClassDeclaration_Behavior.virtual_visibleContentsOfType_7139820346881179813(thisNode, targetConcept);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ClassDeclaration";
  }
}
