package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import com.mbeddr.core.expressions.behavior.ISelfTypingInBinaryExpression_BehaviorDescriptor;
import com.mbeddr.core.pointers.behavior.ISelfTypingInArrayAccessExpression_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class ClassifierType_BehaviorDescriptor extends Type_BehaviorDescriptor implements ITemplateInstantiator_BehaviorDescriptor, ISelfTypingInBinaryExpression_BehaviorDescriptor, ISelfTypingInArrayAccessExpression_BehaviorDescriptor {
  public ClassifierType_BehaviorDescriptor() {
  }

  public boolean virtual_canBeConst_2941277002447374595(SNode thisNode) {
    return ClassifierType_Behavior.virtual_canBeConst_2941277002447374595(thisNode);
  }

  public boolean virtual_canBeVolatile_2941277002449781628(SNode thisNode) {
    return ClassifierType_Behavior.virtual_canBeVolatile_2941277002449781628(thisNode);
  }

  public SNode virtual_getClassDeclaration_1022708226504867673(SNode thisNode) {
    return ClassifierType_Behavior.virtual_getClassDeclaration_1022708226504867673(thisNode);
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return ClassifierType_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  public String virtual_getTemplateSignature_8616684942293463200(SNode thisNode) {
    return ITemplateInstantiator_Behavior.virtual_getTemplateSignature_8616684942293463200(thisNode);
  }

  public SNode virtual_getTypeOfOperation_206521942260333428(SNode thisNode, SNode be) {
    return ClassifierType_Behavior.virtual_getTypeOfOperation_206521942260333428(thisNode, be);
  }

  public SNode virtual_getTypeOfOperation_3285537971614217186(SNode thisNode, SNode aae) {
    return ClassifierType_Behavior.virtual_getTypeOfOperation_3285537971614217186(thisNode, aae);
  }

  public int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return ClassifierType_Behavior.virtual_getUsedBytes_6941595764870551407(thisNode);
  }

  public boolean virtual_isAllowedInBinaryExpression_892278390190633819(SNode thisNode, SNode be) {
    return ClassifierType_Behavior.virtual_isAllowedInBinaryExpression_892278390190633819(thisNode, be);
  }

  public boolean virtual_isAllowedInExpression_3285537971614217179(SNode thisNode, SNode aae) {
    return ClassifierType_Behavior.virtual_isAllowedInExpression_3285537971614217179(thisNode, aae);
  }

  public boolean virtual_isTemplated_8616684942293462842(SNode thisNode) {
    return ITemplateInstantiator_Behavior.virtual_isTemplated_8616684942293462842(thisNode);
  }

  public boolean virtual_requiresTemplateActuals_8616684942293462854(SNode thisNode) {
    return ClassifierType_Behavior.virtual_requiresTemplateActuals_8616684942293462854(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ClassifierType";
  }
}
