package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ClassRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ClassRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ClassRef";
  }
}
