package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class ConceptRestrictedTemplateParameterType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public ConceptRestrictedTemplateParameterType_BehaviorDescriptor() {
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return ConceptRestrictedTemplateParameterType_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ConceptRestrictedTemplateParameterType";
  }
}
