package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;

public class ConceptType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public ConceptType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ConceptType";
  }
}
