package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConceptRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ConceptRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ConceptRef";
  }
}
