package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class Concept_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setNewChild(thisNode, "publicMemberList", "com.mbeddr.cpp.classes.structure.PublicMemberList");
  }

  public static Iterable<SNode> virtual_members_1022708226502685371(SNode thisNode) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "publicMemberList", true), "members", true);
  }

  public static Iterable<SNode> virtual_allMembersOfThisClassOnly_1022708226502685404(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_members_1022708226502685371", new Object[]{});
  }

  public static Iterable<SNode> virtual_externallyVisibleMembers_1022708226502685437(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_members_1022708226502685371", new Object[]{});
  }

  public static Iterable<SNode> virtual_allSuperclasses_1022708226502698814(SNode thisNode) {
    return new ArrayList<SNode>();
  }

  public static Iterable<SNode> virtual_getAllContents_4315577761883431846(SNode thisNode) {
    System.out.println("NOT IMPLEMENTED BEHAVIOR METHOD CALLED in \"Concept\" CONCEPT");
    return null;
  }

  public static Iterable<SNode> virtual_getContents_8928893569897447072(SNode thisNode) {
    System.out.println("NOT IMPLEMENTED BEHAVIOR METHOD CALLED in \"Concept\" CONCEPT");
    return null;
  }

  public static boolean call_isType_292433000620034862(final SNode thisNode) {
    return ListSequence.fromList(SNodeOperations.getDescendants(thisNode, "com.mbeddr.cpp.classes.structure.ConceptType", false, new String[]{})).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, "concept", false) == thisNode;
      }
    });
  }

  public static boolean virtual_exportable_6584628407655574574(SAbstractConcept thisConcept) {
    return true;
  }
}
