package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class ConceptType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public ConceptType_BehaviorDescriptor() {
  }

  public int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return ConceptType_Behavior.virtual_getUsedBytes_6941595764870551407(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ConceptType";
  }
}
