package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class ConstructorCallExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements INewCreator_BehaviorDescriptor, IMethodOrConsCall_BehaviorDescriptor, ITemplateInstantiator_BehaviorDescriptor {
  public ConstructorCallExpression_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_findSiblings_2015268598020361833(SNode thisNode, SNode clazz, String name, boolean internal) {
    return ConstructorCallExpression_Behavior.virtual_findSiblings_2015268598020361833(thisNode, clazz, name, internal);
  }

  public Iterable<SNode> virtual_findSuitableMethodOverloads_2015268598020361784(SNode thisNode, boolean internal, SNode objectType) {
    return IMethodOrConsCall_Behavior.virtual_findSuitableMethodOverloads_2015268598020361784(thisNode, internal, objectType);
  }

  public SNode virtual_getClassDeclaration_1022708226504867673(SNode thisNode) {
    return ConstructorCallExpression_Behavior.virtual_getClassDeclaration_1022708226504867673(thisNode);
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return ConstructorCallExpression_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  public String virtual_getTemplateSignature_8616684942293463200(SNode thisNode) {
    return ITemplateInstantiator_Behavior.virtual_getTemplateSignature_8616684942293463200(thisNode);
  }

  public boolean virtual_isTemplated_8616684942293462842(SNode thisNode) {
    return ITemplateInstantiator_Behavior.virtual_isTemplated_8616684942293462842(thisNode);
  }

  public boolean virtual_requiresTemplateActuals_8616684942293462854(SNode thisNode) {
    return ConstructorCallExpression_Behavior.virtual_requiresTemplateActuals_8616684942293462854(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ConstructorCallExpression";
  }
}
