package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConstructorInitializer_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IInitializerInConstructor_BehaviorDescriptor {
  public ConstructorInitializer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ConstructorInitializer";
  }
}
