package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class Cout_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Cout_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.Cout";
  }
}
