package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class CppNamingConventions_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "MemberPrefix", "m");
    SPropertyOperations.set(thisNode, "GetPrefix", "get");
    SPropertyOperations.set(thisNode, "SetPrefix", "set");
    SPropertyOperations.set(thisNode, "SetterArgPrefix", "the");
  }
}
