package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CppNamingConventions_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CppNamingConventions_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.CppNamingConventions";
  }
}
