package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class DebugArayAccessExpression {
  private static boolean ENABLED = true;

  public static void debug(String str) {
    if (!(ENABLED)) {
      return;
    }
    System.out.println(str + " - " + DebugArayAccessExpression.class.getName());
  }
}
