package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class DeleteArrayStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public DeleteArrayStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.DeleteArrayStatement";
  }
}
