package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class DestructorDeclaration_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_internalName_610576951246057740(SNode thisNode) {
    return SPropertyOperations.getString(IClassMember_Behavior.call_owningClass_998890089994484960(thisNode), "name") + "__" + SPropertyOperations.getString(thisNode, "name");
  }

  public static String call_presentedName_610576951246098939(SNode thisNode) {
    return SPropertyOperations.getString(IClassMember_Behavior.call_owningClass_998890089994484960(thisNode), "name") + "::~" + SPropertyOperations.getString(thisNode, "name");
  }

  public static String call_presentedNameWithSignature_610576951246057790(SNode thisNode) {
    return SPropertyOperations.getString(IClassMember_Behavior.call_owningClass_998890089994484960(thisNode), "name") + "::~" + SPropertyOperations.getString(thisNode, "name") + "()";
  }
}
