package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class FriendClassDeclaration_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getFriend_3152709411796856783(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "friendClass", false);
  }
}
