package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class FriendFunctionDeclaration_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements FriendDeclaration_BehaviorDescriptor {
  public FriendFunctionDeclaration_BehaviorDescriptor() {
  }

  public SNode virtual_getFriend_3152709411796856783(SNode thisNode) {
    return FriendFunctionDeclaration_Behavior.virtual_getFriend_3152709411796856783(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.FriendFunctionDeclaration";
  }
}
