package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface ICanBeInTemplateContext_BehaviorDescriptor {
  public boolean virtual_residesInTemplateContext_998890089994455159(SNode thisNode);
  public Iterable<SNode> virtual_getAllTemplateParameters_7069250747273260302(SNode thisNode);
}
