package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.cpp.cext.behavior.ICppIdentifierNamedConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IDocumentable_BehaviorDescriptor;

public interface IClassMember_BehaviorDescriptor extends ICppIdentifierNamedConcept_BehaviorDescriptor, IDocumentable_BehaviorDescriptor {
}
