package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class IndexExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public IndexExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.IndexExpression";
  }
}
