package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface ITemplateInstantiator_BehaviorDescriptor {
  public boolean virtual_requiresTemplateActuals_8616684942293462854(SNode thisNode);
  public boolean virtual_isTemplated_8616684942293462842(SNode thisNode);
  public SNode virtual_getClassDeclaration_1022708226504867673(SNode thisNode);
  public String virtual_getTemplateSignature_8616684942293463200(SNode thisNode);
}
