package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class OoDotExpression_Behavior {
  public static void init(SNode thisNode) {
  }
}
