package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class OoDotOrArrowExpr_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setNewChild(thisNode, "member", "com.mbeddr.cpp.classes.structure.OoMemberRef");
  }

  public static SNode call_getClassInWhichHappens_7295737679350471120(SNode thisNode) {
    return VisibilityHelper.getClassInWhichAccessHappens(thisNode);
  }
}
