package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class OoFieldAccess_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isLValue_1782955756756783929(SNode thisNode) {
    return !(SPropertyOperations.getBoolean(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "field", false), "type", true), "const"));
  }
}
