package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class OoFieldAccess_BehaviorDescriptor extends OoMemberRef_BehaviorDescriptor {
  public OoFieldAccess_BehaviorDescriptor() {
  }

  public boolean virtual_isLValue_1782955756756783929(SNode thisNode) {
    return OoFieldAccess_Behavior.virtual_isLValue_1782955756756783929(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.OoFieldAccess";
  }
}
