package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class OoMethodCall_BehaviorDescriptor extends OoMemberRef_BehaviorDescriptor implements IMethodOrConsCall_BehaviorDescriptor {
  public OoMethodCall_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_findSiblings_2015268598020361833(SNode thisNode, SNode clazz, String name, boolean internal) {
    return OoMethodCall_Behavior.virtual_findSiblings_2015268598020361833(thisNode, clazz, name, internal);
  }

  public Iterable<SNode> virtual_findSuitableMethodOverloads_2015268598020361784(SNode thisNode, boolean internal, SNode objectType) {
    return IMethodOrConsCall_Behavior.virtual_findSuitableMethodOverloads_2015268598020361784(thisNode, internal, objectType);
  }

  public boolean virtual_isLValue_1782955756756783929(SNode thisNode) {
    return OoMethodCall_Behavior.virtual_isLValue_1782955756756783929(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.OoMethodCall";
  }
}
