package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class OoMemberRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public OoMemberRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.OoMemberRef";
  }

  public abstract boolean virtual_isLValue_1782955756756783929(SNode thisNode);
}
