package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class PrimitiveTemplateParamRef_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isLValue_7254843406768839725(SNode thisNode) {
    return false;
  }

  public static boolean virtual_isStaticallyEvaluatable_3788988821852141811(SNode thisNode) {
    return true;
  }
}
