package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class PrimitiveTemplateParamRef_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public PrimitiveTemplateParamRef_BehaviorDescriptor() {
  }

  public boolean virtual_isLValue_7254843406768839725(SNode thisNode) {
    return PrimitiveTemplateParamRef_Behavior.virtual_isLValue_7254843406768839725(thisNode);
  }

  public boolean virtual_isStaticallyEvaluatable_3788988821852141811(SNode thisNode) {
    return PrimitiveTemplateParamRef_Behavior.virtual_isStaticallyEvaluatable_3788988821852141811(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.PrimitiveTemplateParamRef";
  }
}
