package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class PrivateMemberList_BehaviorDescriptor extends MemberList_BehaviorDescriptor {
  public PrivateMemberList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.PrivateMemberList";
  }
}
