package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class ProtectedMemberList_BehaviorDescriptor extends MemberList_BehaviorDescriptor {
  public ProtectedMemberList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ProtectedMemberList";
  }
}
