package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class SquareBracketsOperatorDesignator_BehaviorDescriptor extends OperatorDesignatorAbstract_BehaviorDescriptor {
  public SquareBracketsOperatorDesignator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.SquareBracketsOperatorDesignator";
  }
}
