package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class TemplatePrimitiveParameter_BehaviorDescriptor extends TemplateParameter_BehaviorDescriptor {
  public TemplatePrimitiveParameter_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.TemplatePrimitiveParameter";
  }
}
