package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class TemplateClassParameter_BehaviorDescriptor extends TemplateParameter_BehaviorDescriptor {
  public TemplateClassParameter_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.TemplateClassParameter";
  }
}
