package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class ThisExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ThisExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.cpp.classes.structure.ThisExpression";
  }
}
