package com.mbeddr.cpp.classes.behavior;

/*Generated by MPS */


public class VisibilityStrategyFactory {
  private static ICppMemberVisibilityStrategy instance = new CppMemberVisibilityStrategy();

  public static ICppMemberVisibilityStrategy getStrategy() {
    return instance;
  }
}
