package com.mbeddr.cpp.cext.typesystem;

/*Generated by MPS */


public class NamespaceTypeSystemDebug {
  private static boolean ENABLED = false;

  public static void debug(String s) {
    if (!(ENABLED)) {
      return;
    }
    System.out.println(s + " -- " + NamespaceTypeSystemDebug.class.getName());
  }
}
