package com.mbeddr.cpp.classes.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class MemberList_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.increaseDepth();
    this.indentBuffer();
    this.append(SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(node), "conceptAlias"));
    this.append(":");
    this.appendNewLine();
    this.increaseDepth();
    for (SNode m : ListSequence.fromList(SLinkOperations.getTargets(node, "members", true))) {
      this.indentBuffer();
      TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), m, this.getSNode());
    }
    this.decreaseDepth();
    this.decreaseDepth();
  }
}
