package com.mbeddr.cpp.classes.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class TemplateClassParameter_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("class ");
    this.append(SPropertyOperations.getString(node, "name"));
  }
}
