package com.mbeddr.cpp.cext.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ConvertToImplementationModule_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ConvertToImplementationModule_Intention() {
  }

  public String getConcept() {
    return "com.mbeddr.cpp.cext.structure.CppImplementationModule";
  }

  public String getPresentation() {
    return "ConvertToImplementationModule";
  }

  public String getPersistentStateKey() {
    return "com.mbeddr.cpp.cext.intentions.ConvertToImplementationModule_Intention";
  }

  public String getLanguageFqName() {
    return "com.mbeddr.cpp.cext";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return (SNodeOperations.getParent(node) == null);
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:ab2eb74f-bdf7-4f08-839c-11455dff83d4(com.mbeddr.cpp.cext.intentions)", "4387763778170604919");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ConvertToImplementationModule_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Convert to C Implementation Module";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SNode im = SConceptOperations.createNewNode("com.mbeddr.core.modules.structure.ImplementationModule", null);
      SModelOperations.addRootNode(SNodeOperations.getModel(node), im);
      SPropertyOperations.set(im, "name", SPropertyOperations.getString(node, "name"));
      ListSequence.fromList(SLinkOperations.getTargets(im, "smodelAttribute", true)).addSequence(ListSequence.fromList(SLinkOperations.getTargets(node, "smodelAttribute", true)));
      ListSequence.fromList(SLinkOperations.getTargets(im, "imports", true)).addSequence(ListSequence.fromList(SLinkOperations.getTargets(node, "imports", true)));
      ListSequence.fromList(SLinkOperations.getTargets(im, "contents", true)).addSequence(ListSequence.fromList(SLinkOperations.getTargets(node, "contents", true)));
      SNodeOperations.deleteNode(node);
    }

    public IntentionDescriptor getDescriptor() {
      return ConvertToImplementationModule_Intention.this;
    }
  }
}
