package com.mbeddr.cpp.cext.intentions;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ModuleRefMaker {
  public static SNode fromModule(SNode mod) {
    SNode res = SConceptOperations.createNewNode("com.mbeddr.core.buildconfig.structure.ModuleRef", null);

    SLinkOperations.setTarget(res, "module", mod, false);

    return res;
  }
}
