package com.mbeddr.cpp.cext.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ToggleAnonymousNamespace_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ToggleAnonymousNamespace_Intention() {
  }

  public String getConcept() {
    return "com.mbeddr.cpp.cext.structure.Namespace";
  }

  public String getPresentation() {
    return "ToggleAnonymousNamespace";
  }

  public String getPersistentStateKey() {
    return "com.mbeddr.cpp.cext.intentions.ToggleAnonymousNamespace_Intention";
  }

  public String getLanguageFqName() {
    return "com.mbeddr.cpp.cext";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:ab2eb74f-bdf7-4f08-839c-11455dff83d4(com.mbeddr.cpp.cext.intentions)", "2017510268494218938");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ToggleAnonymousNamespace_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Toggle Anonymous";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SPropertyOperations.set(node, "anonymous", "" + (!(SPropertyOperations.getBoolean(node, "anonymous"))));
    }

    public IntentionDescriptor getDescriptor() {
      return ToggleAnonymousNamespace_Intention.this;
    }
  }
}
